server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务器地址
        namespace: OnlineMall
        group: TEST_GROUP
    gateway: # 自定义路由配置
      routes:
        - id: user-service  # 路由ID，唯一标识
          uri: lb://user-service  # 目标服务地址，lb表示负载均衡
          predicates: # 路由断言，匹配请求路径
            - Path=/user/**
        - id: product-service  # 路由ID，唯一标识
          uri: lb://product-service  # 目标服务地址，lb表示负载均衡
          predicates: # 路由断言，匹配请求路径
            - Path=/product/**
        - id: review-service  # 路由ID，唯一标识
          uri: lb://review-service  # 目标服务地址，lb表示负载均衡
          predicates: # 路由断言，匹配请求路径
            - Path=/review/**
        - id: cart-service  # 路由ID，唯一标识
          uri: lb://cart-service  # 目标服务地址，lb表示负载均衡
          predicates: # 路由断言，匹配请求路径
            - Path=/cart/**,/favorites/**