server:
  port: 8084
spring:
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务器地址
        namespace: OnlineMall
        group: TEST_GROUP
  datasource: #配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_mall_cart
    username: root
    password: admin123
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名自动映射